package faplib;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JMenuItem;

/**
 * <b>frmMain est la classe représentant la fenêtre principale de l'application</b> 
 * @see frmMain
 * @author LoliveSerious
 * @version 1.0 
 */
public class frmMain extends javax.swing.JFrame {

    private JMenuItem frmStage;

    /**
     * Classe qui initialise des constructeurs et ...
     */
    public frmMain() {
        
        //Initialisation constructeurs
        initComponents();
        initDesktop();
//        ImageIcon img = new ImageIcon("..\\images\\smiley.png");
//        img.setIconImage(img.getImage());
        
        //fermeture application via jdialog
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e){
                if (JOptionPane.showConfirmDialog(null, "Aller voir ailleurs?", "NON!... SERIEUX?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    dispose();
                    System.exit(0);
                }
            }
        }); 
        
        //Insertion d'une icône pour la fenêtre
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("..\\FAPLIB\\src\\images\\Smiley.png");
        setIconImage(img);
        
        
    }
    
     /**
    * Constructeur qui regroupe:
    * <ul>
    * <li>toolbar avec boutons</li>
    * <li>Emplacement des fenêtres internes</li>
    * </ul>
    */
    private void  initDesktop(){
        
        //Ajout d'un jDesktopPane pour y mettre des jInternalFrame
        this.add( theDesktop );
        theDesktop.setSize(this.getWidth(), this.getHeight());
        theDesktop.putClientProperty("JDesktopPane.dragMode","outline");
        theDesktop.setBackground(Color.darkGray);

        //position des éléments de la fenêtre principale
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add("North", jToolBar1);
        getContentPane().add("Center", theDesktop);
        
        
    }
    
    /**
     * Création des boutons, toolbar, menus, labels et autres paramètres définis via les options... 
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        jMenuItem17.setText("jMenuItem17");
        jPopupMenu1.add(jMenuItem17);

        jMenuItem18.setText("jMenuItem18");
        jPopupMenu1.add(jMenuItem18);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FAP");
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Help Purple Button.png"))); // NOI18N
        jButton2.setToolTipText("Aide");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Quitter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Données");

        jMenuItem2.setText("Stages");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Entreprise");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Types");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Evénements");

        jMenuItem5.setText("Inscription");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Absence");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Paiement");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Affichage");

        jMenuItem8.setText("Barre d'outils");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Barre d'état");
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Fenetre");

        jMenuItem10.setText("En cascade");
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Mosaîque horizontale");
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Mosaîque verticale");
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("Réorganiser les icônes");
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("?");

        jMenuItem14.setText("Sommaire");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("Aide sur...");
        jMenu6.add(jMenuItem15);

        jMenuItem16.setText("A propos de");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem19.setText("Contact");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem19);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 484, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ouverture de la fenêtre interne frmStage
     * @see frmStage
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmStage stage = new frmStage();
        theDesktop.add(stage);      
        stage.setVisible(true);

        try {
            stage.setSelected(true);
            stage.setMaximum(true);//maximise la fenêtre
//            jMenuItem2.setEnabled(false);
            
            
        } catch (java.beans.PropertyVetoException e) {}  
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    /**
     * ouverture de la fenêtre Apropos 
     * @see Apropos
     */
    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Apropos dlg = new Apropos(this, "FAP");
        dlg.setDescription("Une description vraiment débile\n"
                            /*+ "(c) LoliveSerious 2016\n"
                            + "Version 1.0.test.1"*/);
        dlg.setCopyright("LoliveSerious (c) 2016");
        dlg.setVersion("Version 1.0.test.1");
        dlg.setIcone("..\\FAPLIB\\src\\images\\lolive.jpg");
        dlg.show();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    /**
     * Permet de quitter l'application via l'action quitter du menu.
     * Affiche une boîte de confirmation.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       if (JOptionPane.showConfirmDialog(null, "Aller voir ailleurs?", "NON!... SERIEUX?",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * ouverture de la fenêtre interne frmEnt
     * @see frmEnt
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       frmEnt If = new frmEnt();
        theDesktop.add(If);
        If.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * ouverture de la fenêtre secondaire MailApp
     * @param evt 
     */
    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        MailApp contact = new MailApp();
        contact.show();    
    }//GEN-LAST:event_jMenuItem19ActionPerformed
    
    /**
     * Fenêtre principale maximisé
     * @param evt 
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
//        this.setExtendedState(JInternalFrame.IS_MAXIMUM_PROPERTY | this.getExtendedState);
    }//GEN-LAST:event_formWindowOpened
  
    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);   
            }
        });     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    public static javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    // others Variables declaration 
    public static final JDesktopPane theDesktop = new JDesktopPane();

    private void setFrameIcon(ImageIcon imageIcon) {

    }

}
